### ISSUE TITLE
Switch from using iModels V1 API to V2

### ISSUE THREAD

**Issue by grigasp** [iTwin/presentation-rules-editor#152]
![Image](https://github.com/iTwin/presentation-rules-editor/assets/35135765/ac81903b-fc9a-410e-9ed8-6f1d6ef8fd26)

The V1 API is about to be turned off, need to switch to using V2. Docs: https://developer.bentley.com/apis/imodels/overview/#howtouseimodelsapiv2version

**Comment by grigasp** [comment]
Let's close this when a new version with these changes is deployed.

**Comment by saskliutas** [comment]
Changes are deployed.
